default: &default
  host: "localhost"
  port: 3306
  user: root
  pass: root
  database: orm_mysql_prod

dev:
  <<: *default

prod:
  <<: *default
  user: <%= ENV["MYSQL_PORT"] || "3306" %>
  pass: <%= ENV["MYSQL_HOST"] || "localhost" %>
  user: <%= ENV["MYSQL_USER"] || "root" %>
  pass: <%= ENV["MYSQL_PASS"] || "root" %>
  database: <%= ENV["MYSQL_DATA"] || "orm_mysql_prod" %> 